### ISSUE TITLE
os

### ISSUE THREAD

**Issue by watanabenaoyuk** [watanabenaoyuk/oss-enterprise#2]
### Details

when running npx create-react-app my-app I get this error and it tells me to report this as a bug.

### Node.js version

v16.14.2

### Example code

npx create-react-app my-app

### Operating system

windows 11

### Scope

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...

Aborting installation.
Unexpected error. Please report it as a bug:
Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:700:9)
    at spawn (C:\Users\steel\AppData\Roaming\npm\node_modules\create-react-app\node_modules\cross-spawn\index.js:12:24)
    at C:\Users\steel\AppData\Roaming\npm\node_modules\create-react-app\createReactApp.js:390:19
    at new Promise (<anonymous>)
    at install (C:\Users\steel\AppData\Roaming\npm\node_modules\create-react-app\createReactApp.js:341:10)
    at C:\Users\steel\AppData\Roaming\npm\node_modules\create-react-app\createReactApp.js:468:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawn'
}

Deleting generated file... package.json
Deleting my-app/ from D:\testreact
Done.

### Module and version

Not applicable.

_オリジナルは @justincando が https://github.com/nodejs/help/issues/3819 にポスト_渡邉直行

**Comment by watanabenaoyuk** [comment]
渡邉直行


naoyukiwatnabe@docnmo.ne.jp
iphone6.naoyuki@gmail.com
